# Generated by Django 4.1 on 2023-09-25 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='description',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='image1',
            new_name='gambar1',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='image2',
            new_name='gambar2',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='name',
            new_name='nama_barang',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='tipe',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='views',
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.CharField(default=datetime.datetime(2023, 9, 25, 2, 2, 22, 93391, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produk',
            name='rating',
            field=models.FloatField(),
        ),
    ]
